---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bggapp-deploy
  name: bggapp-deploy
  namespace: bggns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bggapp-deploy
  template:
    metadata:
      labels:
        app: bggapp-deploy
    spec:
      containers:
      - image: stackupiss/bgg-backend:v1
        name: bgg-backend
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          periodSeconds: 60
        envFrom:
        - configMapRef:
            name: bgg-cm
        - secretRef:
            name: bgg-secret
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bgg
spec:
  type: ClusterIP
  selector:
    app: bggapp-deploy
  ports:
  - port: 80
    targetPort: 3000